# -*- coding: utf-8 -*-
"""VLM model test 2: electric boogaloo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EiOOmqF12VslBHIjN1FQMpfOhf3VTBiL
"""

!pip install playwright
!playwright install-deps firefox
!pip install supervision

import supervision as sv
import io
from PIL import Image

from time import sleep

from google.colab import output

import asyncio
from playwright.async_api import async_playwright

"""Set up the live feed"""

playwright = None
browser = None
context = None
page = None

async def setup():
  global playwright, browser, context, page
  playwright = await async_playwright().start()
  browser = await playwright.firefox.launch(
      headless = True,
      args=["--autoplay-policy=no-user-gesture-required"]
      )
  context = await browser.new_context(
      extra_http_headers = {"referer": "https://example.com/"}
      #needs this to avoid Error 153 (https://stackoverflow.com/questions/79802987/youtube-error-153-video-player-configuration-error-when-embedding-youtube-video)
      )
  page = await context.new_page()
  await page.goto("https://www.youtube.com/embed/1H0iTzv2jiQ?autoplay=1&mute=1") #ONLY change the ID (the stuff between embed/ and ?autoplay)
  await asyncio.sleep(1)

async def close_browser():
  await browser.close()
  await playwright.stop()

async def prt_sc():
  image = await page.screenshot()
  return Image.open(io.BytesIO(image))

await(setup())

"""Benchmark function"""

def benchmark(): #wip
#gonna ask the model to count red cars or sth
  return 1

"""Main loop"""

for i in range(10):
  sv.plot_image(await(prt_sc()))
  benchmark() #<- goes here, then get the average response time of every loop
  sleep(1)
  output.clear()

await(close_browser()) #run as needed